### ISSUE TITLE
Dúvida sobre repositórios participantes

### ISSUE THREAD

**Issue by mateusKoppe** [ccuffs/hacktoberfest#1]
Olá, fiquei com uma dúvida sobre quais repositórios estão "participando" do hacktoberfest, no regulamento consta que basta contribuir em qualquer repositório da organização Ccuffs, porém abaixo da tabela de quantidade de PR/prêmio existe uma observação listando os repositórios válidos, fiquei um pouco confuso quanto a isso, o que vale são os repositórios listados ou qualquer repositório na organização?

Caso seja a lista que vale, posso solicitar a adição de um novo repo da organização nessa lista para validar meus PRs?

Caso alguém ou algum grupo tome a iniciativa de criar um projeto na organização os PRs nesse projeto serão avaliados?

**Comment by Dovyski** [comment]
**Todos** os repositórios listados em [https://github.com/ccuffs/](https://github.com/ccuffs/) e que _não sejam forks_ estão valendo para o hacktoberfest. A observação que existe abaixo da tabela de premiação é referente ao prêmio:

> Coordenador trabalha um dia inteiro usando um sombreiro Mexicano

Para conseguir esse prêmio, a pessoa precisa fazer 16 PRs (há um asterísco ao lado do 16, e a informação desse astesrisco é a observação que você mencionou).

Ficou mais claro?

**Comment by Dovyski** [comment]
> Caso alguém ou algum grupo tome a iniciativa de criar um projeto na organização os PRs nesse projeto serão avaliados?

Sim, porém esse projeto precisa ter algum norte. Por exemplo, um bot de telegram para o curso.

**Comment by mateusKoppe** [comment]
Show! Obrigado pela resposta :D
