### ISSUE TITLE
Links com erro

### ISSUE THREAD

**Issue by patrickluzdev** [ccuffs/hacktoberfest#2]
** DescrIção o bug/problema **

Algun links no arquivo  README.md não estão funcionando corretamente, aparentemente  não estão encontrando a página de destino. 

**Reproduzir**
Etapas para reproduzir o problema:
1. Acesse o link:  https://uffs.cc/hf
2. Clique na aba CODE  do repositório
3. Acesse os links disponiveis no README.MD

**Comportamento esperado**
Era para um dos links redirecionar o usuário para o perfil de computação da no Github: https://github.com/ccuffs
O outro link era para redirecionar o usuário para o próprio repositório:  https://uffs.cc/hf

Links com ERROR 404:
- https://github.com/ccuffs/hacktoberfest/blob/master/uffs.cc/hf
- https://github.com/ccuffs/hacktoberfest/blob/master/github.com/ccuffs

** Capturas de tela **

![Capturar](https://user-images.githubusercontent.com/44445007/96034200-8d354200-0e37-11eb-8789-0add2d011cf0.PNG)

** Desktop (preencha as seguintes informações): **
  - Sistema operacional: Windows
  - Navegador: Chrome

**Comment by Dovyski** [comment]
Os links foram corrigidos. Obrigado pelo report! ❤️ 🥳
